/* Motor nuevo: genera las 2 páginas de cada capítulo al vuelo. */
const paper=document.querySelector('#paper'),label=document.querySelector('#label');
const totalPages=CHAPTERS.length*2+2;let position=0;
function escapeHTML(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function show(content,kind=''){paper.className=`paper ${kind}`;paper.innerHTML=content}
function cover(){show('<p class="season">TÉCNICA 9 · 1RO 2DA</p><h1>EL AULA QUE<br>APRENDIÓ A ESCUCHARSE</h1><p>Una historia de nueve temporadas</p><p><b>Escritor: primero segunda</b></p><p>“Nadie aprende solo porque…”</p>','cover');label.textContent='Portada'}
function back(){show('<p class="season">CONTRATAPA</p><h2>La última página también enseña</h2><p>“…nadie llega al final sin que alguien le enseñe una parte del camino.”</p><p>Fin.</p>','cover');label.textContent='Contratapa'}
function chapter(){const index=Math.floor((position-1)/2),part=((position-1)%2)+1,c=CHAPTERS[index];const extra=part===2?'Tomás organizó las propuestas, Agustina ayudó a encontrar un acuerdo y Micaela reunió los materiales. Sandra, la preceptora, observó cómo el curso convertía el problema en una experiencia compartida.':'';show(`<p class="season">${escapeHTML(c.season)}</p><h2>Capítulo ${c.num}<br>${escapeHTML(c.title)}</h2><p><b>Docente:</b> ${escapeHTML(c.teacher)}</p><p>${escapeHTML(c.text)}</p>${extra?`<p>${extra}</p>`:''}<span class="number">Página ${part} de 2</span>`);label.textContent=`Capítulo ${c.num} · página ${part} de 2`}
function render(){if(position===0)cover();else if(position===totalPages-1)back();else chapter();document.querySelector('#prev').disabled=position===0;document.querySelector('#next').disabled=position===totalPages-1}
function move(step){const next=position+step;if(next<0||next>=totalPages)return;paper.classList.add('turn');setTimeout(()=>{position=next;render();paper.classList.remove('turn')},350)}
document.querySelector('#next').onclick=()=>move(1);document.querySelector('#prev').onclick=()=>move(-1);document.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key===' ')move(1);if(e.key==='ArrowLeft')move(-1)});document.querySelector('#full').onclick=()=>document.documentElement.requestFullscreen?.();render();